public class Constants {
	public final static String ATM_FEE = 'ATMFee';
    public final static String REPLACEMENT_COST = 'ReplacementCost';
    public final static String COST_PER_MONTH = 'CostPerMonth';
    public final static String CURRENCY_CODE = 'CurrCode';
    public final static String PRODUCT_NAME = 'ProdName';
    public final static String CONTRACT_TERM = 'ContractTerm';
    public final static String CONTRACT_LINK = 'ContractLink';
    
    public final static String CONTRACT_EXISTS = 'ContractExist';
    public final static String PRODUCT_INFO = 'ProductInfo';
    
    public final static String PRODUCT_LINK = 'ProductLink';
}