global class ResponseWrapper {
    global String Home_Country{get; set;}
    global Boolean ContractExist{get; set;}
    global Decimal ATMFee{get; set;}
    global Decimal ReplacementCost{get; set;}
    global Decimal CostPerMonth{get; set;}
    global String CurrencyCode{get; set;}
    global String ProductName{get; set;}
    global Integer ContractTerm{get; set;}
    global Id ContractId{get; set;}
    global Id ProductId{get; set;}
    
    //global Map<String,Object> ProductInformation{get; set;}
}